### ISSUE TITLE
Tools do not work properly with paper.js v0.9.25

### ISSUE THREAD

**Issue by pulse-kostis** [nicholaswmin/vectorCake#1]
Can select but cannot resize or rotate

**Comment by nicholaswmin** [comment]
Can you give me a repro case please?

Things like:
- steps to reproduce
- browser you're seeing this

would help.

**Comment by pulse-kostis** [comment]
Hi, thanks for the reply. I am trying to embed your editor to my project Please take a look at the sample project I have sent to your email (not allowed to upload here).
Thanks again.

**Comment by nicholaswmin** [comment]
Sorry mate can't and won't do. Time's limited.

If there's an issue on this repo let me know and i'll patch it up (or you can submit a PR if you solve it and I'll merge it).

You can also shoot questions if there's something that's unclear in the codebase.

**Comment by pulse-kostis** [comment]
Ok. Thanks

**Comment by nicholaswmin** [comment]
Do you get any console errors for this?

**Comment by pulse-kostis** [comment]
No. just does not work.However, when reverting to paper.0.9.24, everything works fine.

**Comment by nicholaswmin** [comment]
Allright mate thanks - I'll take a look when things clear up

**Comment by nicholaswmin** [comment]
@pulse-kostis 

I'm running a bit low on time unfortunately. Signomi file :)
- Unless you _really, really_ need to use paper `0.9.25 +` you can just use paper `0.9.24` until I dive into this.

I don't see anything that would break the API (or the way Tools are implemented), so when I do the update fix anyway you can just `git pull` - without your new code breaking at all.

Sounds good?

**Comment by pulse-kostis** [comment]
You are right..it is something in my project that breaks its functionality. I tested 0.9.25 in your project and it worked ok so no need from you to do something.  I need to investigate more on this.

Thanks for your interest though file.

**Comment by nicholaswmin** [comment]
All right then good luck on your end - Closing.
