### ISSUE TITLE
Can't undo the first move action

### ISSUE THREAD

**Issue by pulse-kostis** [nicholaswmin/vectorCake#2]
In the sample index file, cannot undo the first move action.

Chrome / Win 7

**Comment by pulse-kostis** [comment]
It is happening when select-drag the image and then undo(nothing happens then)

**Comment by nicholaswmin** [comment]
Thanks - will take a look tomorrow most probably.

**Comment by nicholaswmin** [comment]
It's probably somewhere around here: in `tools/selectionTools.js`: 

```
  mouseup: function(event) {
    if (this.mode == 'move-shapes') {
      if (this.changed) { // `changed is set at false` on mousedown. Perhaps move `undo.snapshot` outside this if.
        clearSelectionBounds();
        undo.snapshot("Move Shapes");
      }
      this.duplicates = null;
    } else if (this.mode == 'box-select') {
      var box = new paper.Rectangle(this.mouseStartPos, event.point);

      if (!event.modifiers.shift)
        deselectAll();

      var selectedPaths = getPathsIntersectingRect(box);
      for (var i = 0; i < selectedPaths.length; i++)
        selectedPaths[i].selected = !selectedPaths[i].selected;
    }
```

**Comment by nicholaswmin** [comment]
@pulse-kostis 

So the reason you can't undo the first state is this:
- The Undo system uses _snapshots_ of states (current drawings/items/positions) on the canvas.
- When that Marilyn test `Raster` is created **no initial saving of the 1st initial state exists** therefore you can't undo what's already on the canvas

### Here's the part that interests you:
- I don't believe you need the Marilyn Raster in your project so if you want to save the initial state just `importJSON()` or create whatever "startup" `Item`'s you need and then call:
  -  `undo.snapshot("Initial State");`
- The method for saving an Undo snapshot is this: 
  - `undo.snapshot([snapshot name])`;
- I've already pushed some code that takes that snaphot right after that test Marilyn image is created so it should work now even with that test image.
