### ISSUE TITLE
Zoom to mouse point does not work on firefox and chrome

### ISSUE THREAD

**Issue by pulse-kostis** [nicholaswmin/vectorCake#3]
Hi Nick, I am trying to get the zoom tool to zoom to mouse pointer on the main browsers Chrome and FF but with no luck till now. In chrome it works when there is no html element before the canvas element, while on FF it fails in every html code. I am attaching the html code. The js is exactly the same as in vectorCake zoom tool. I cannot get it as what is the problem: just zoom.js code or some combination of js, html and css?

Thanks.

**Comment by nicholaswmin** [comment]
Thanks,

I have an idea on how to fix it. 
I'll give it some love mid-week when things clear up on my end.

No need to attach code :) The repo has the code in and by itself.

**Comment by nicholaswmin** [comment]
Also, avoid placing HTML elements in front of the canvas.

As expected, they will block consumption of mouse-`events` by the `canvas` thus completely blocking any kind of interaction with it.

Or you can mitigate this by using `pointer-events: none` CSS on the blocking HTML element. 
Another possible solution is piggy-backing on the DOM-tree's event-bubbling concepts by nesting properly your HTML elements in such a way that the mouse-`event` is correctly propagated to the canvas.

---

**Long-story short:**

If you want any kind of mouse-interaction with the canvas, the `events` need to eventually reach the canvas.

**Comment by pulse-kostis** [comment]
Ok, when you say 'in front of the canvas' do you mean before the canvas element in the html file?
I will try you suggestions and let you know.
Thanks.

**Comment by nicholaswmin** [comment]
> In front of the canvas

This means _below the `<canvas>` in the DOM tree OR in any way positioned on top of the `<canvas>` using CSS._

An example:

![Image showing the console of a DOM tree where <canvas> is below(after) <div class="tools-left">](https://cloud.githubusercontent.com/assets/3926463/14432061/26c99644-0011-11e6-821c-5b3aad55583b.png)

In the above example `tools-left` are _before_ the `<canvas>` (assuming no CSS are re-positioning `tools-left`). You could say that in this example `tools-left` are positioned _below_ the `<canvas>`. 

If the opposite order occured in the DOM-tree (`<tools-left>` were after the `<canvas`>) then the opposite would occur as well in terms of stacking(who's on top of who).

This is, more or less, basic stuff and it might be useful to read up on [The Stacking Context (z-index)](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context) if you're having problems with it. 

A dummy sanity test for this is right clicking on where the `<canvas>` is supposed to be. If the right-click menu contains only canvas related stuff (e.g Save Image As../Copy Image As../Inspect Element) then nothing is blocking the canvas. If it has more stuff than the aforementioned, then another HTML element is blocking your `<canvas>`.

**Do note that I confirm that there is a bug on zoom in Firefox/Safari** so if that's the issue you're experiencing I highly doubt is connected to whatever you are doing yourself. It's a bug that I need to fix in the code.

Cheers,

N

**Comment by pulse-kostis** [comment]
By the way the sanity test you suggested shows the the canvas related stuff(save image, copy image, inspect element)

**Comment by nicholaswmin** [comment]
It's the bug then - Ignore FF/Safari issues and I'll fix it in the code.

**Comment by pulse-kostis** [comment]
Thanks Nick

**Comment by nicholaswmin** [comment]
@pulse-kostis fixed - now it zooms to point on Firefox/Safari/Chrome - Haven't tested IE as I'm on OSX, but I don't think there's gonna be any problems there.

**Comment by pulse-kostis** [comment]
Thanks for the fix. It now zooms the same way to chrome and ff (not test safari) but it cannot zoom to point. I don't move the mouse pointer while scrolling and the canvas content goes to left, just like before your fix.

![capture](https://cloud.githubusercontent.com/assets/5339547/14455920/d79c682c-00aa-11e6-9d8e-352e4989030b.JPG)
![capture2](https://cloud.githubusercontent.com/assets/5339547/14455921/d7a054d2-00aa-11e6-981a-ae9e950d1dc8.JPG)

Thanks.

**Comment by nicholaswmin** [comment]
Are you testing from `master` branch or on the demo-pages (nicholaswmin.github.io/vectorCake) ?

**Comment by nicholaswmin** [comment]
In any case, I've just pushed to the [demo-pages](https://nicholaswmin.github.io/vectorCake) as well so it should be fixed there too.

**Comment by pulse-kostis** [comment]
It works on demo pages but something in my html is affecting the zoom action. When I remove a div element that is before the canvas element (however, there are some elements left before the canvas), then it works.

**Comment by nicholaswmin** [comment]
Your HTML elements are probably messing with the canvas position/size. I can't think of any other explanation for what you're seeing.

The `zoom` functionality assumes that the `canvas` takes the _whole viewport/window width_. Any other size than that is going to cause issues.

**Comment by pulse-kostis** [comment]
I am not sure about this since when I remove the div element 'side' before the canvas, it works even if canvas does not take the whole window width.

**Comment by nicholaswmin** [comment]
> when I remove the div element 'side' before the canvas

Not sure I'm following what you mean here.
One thing I know for certain is that it won't work properly if the circumstances are not what I described in my last comment.

But if you still think this is a problem with the repo's code and the interactions with additional HTML elements then hack up a small [JSFiddle](http://jsfiddle.net/) for me  and I promise I'll take a peek. 

Make sure it's an [MVCE-type](http://stackoverflow.com/help/mcve) of JSFiddle so I don't have to sift through unrelated code.

Sounds good?

**Comment by pulse-kostis** [comment]
I mean that I put the canvas element in a html layout that is being styled by bootstrap, not the way you put it in your project. The div that canvas rests is between two other 'side' divs in the html code I sent in the file in first comment, but the sanity test shows the 3 expected options when right-clicking on it. I need to investigate this. 
Thanks.

**Comment by nicholaswmin** [comment]
You're prolly using Bootstrap's grid system - right?

Like having 3 columns and the middle one hosts the `<canvas>` - Am I right?

If that's the case then the `<canvas>` doesn't take up the whole viewport/window width thus it won't work properly. Best case scenario is that the zoom-homing would be offset from the correct homing-point.

There might be an easy fix in the repo's code for this but you need to confirm to me that the circumstances are what I describe above.

**Comment by nicholaswmin** [comment]
Pushed a fix, try again from `master` branch and let me know if it's better.

**Comment by pulse-kostis** [comment]
You are the best my friend. It worked both in chrome and FF.
Εύγε!!!

**Comment by pulse-kostis** [comment]
Regarding the layout scenario, yes this is what I use. Three columns and the canvas rests in the middle one.
Thanks

**Comment by nicholaswmin** [comment]
Nice work mate - Keep on pushin'

![05d](https://cloud.githubusercontent.com/assets/3926463/14491779/851e0734-0183-11e6-8964-aabcc36731d7.jpg)
